### ISSUE TITLE
Add ability to set attributes in `set` commands

### ISSUE THREAD

**Issue by pmarini** [canonical/lxd#10960]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-47-generic
   * LXC version:
   * LXD version: 5.6
   * Storage backend in use: zfs

# Issue description

What I’m looking for is something like:

`
lxc <object> set description "My Nice Object"
`

that would generally work for all the objects: storage pools, networks, projects, profiles, containers…

# Steps to reproduce

Just run the above command, that fails.

# Information to attach

**Comment by pmarini** [comment]
Thanks @tomponline for the feedback.

My intention was to have what you describe as `lxc set-description "My description"`.

As of now description cannot be automated via the lxc command line.

**Comment by stgraber** [comment]
I'm not super keen on `set-description` because that's a whole separate command which will need to be replicated for every single object across the whole API, so we're looking at another 15+ commands, each with their own help, manpage, ...

And that only sets a single attribute. Say you now want to set a snapshot expiry, we'd be back to adding `set-snapshot-expiry` on instance and volume snapshots, ...

I suspect whatever we do will feel like a hack unfortunately. I guess one option would be to have `lxc config set --attribute foo description blah` to make it clear that we're trying to modify an attribute and not a config key.

To do that, we'd need to make it consistent though, so we'd need that same `--attribute` supported on every `set` command as well as `unset` and `get`. We also don't want to start hardcoding keys, so we'd need a function which can use reflect to inspect the struct, match the field and set it. As that field may not just be a string, we'd need it to support at least handling of strings, integers and timestamps.

**Comment by tomponline** [comment]
> I suspect whatever we do will feel like a hack unfortunately.

I suppose we could have `lxc set description=foo` and just ensure that we never use `description` in an entity's config.

Not ideal, but given its an established system and AFAIK we don't use `description` in config anywhere, it feels like it would be the smallest change.




> I suspect whatever we do will feel like a hack unfortunately. I guess one option would be to have `lxc config set --attribute foo description blah` to make it clear that we're trying to modify an attribute and not a config key.
> 
> To do that, we'd need to make it consistent though, so we'd need that same `--attribute` supported on every `set` command as well as `unset` and `get`. We also don't want to start hardcoding keys, so we'd need a function which can use reflect to inspect the struct, match the field and set it. As that field may not just be a string, we'd need it to support at least handling of strings, integers and timestamps.

That would certainly be a more thorough and cleaner approach.

**Comment by stgraber** [comment]
> I suppose we could have `lxc set description=foo` and just ensure that we never use `description` in an entity's config.
> 
> Not ideal, but given its an established system and AFAIK we don't use `description` in config anywhere, it feels like it would be the smallest change.

`description` is an actively used config key on our images at least, so we can't do that.
We also have a lot more properties we may want to set and I'd rather not have to ban all of those from configs across all of LXD.

**Comment by cilex-ft** [comment]
@pmarini Perhaps this hack https://github.com/lxc/lxd/issues/11062 might help? I tried out of desperation & it worked...

**Comment by pmarini** [comment]
> @pmarini Perhaps this hack #11062 might help? I tried out of desperation & it worked...

Thanks @cilex-ft. I see that this feature may be developed.
