### ISSUE TITLE
hot-unplug on device succeeded but the virtual machine seems to be corrupted 

### ISSUE THREAD

**Issue by georgeliao** [canonical/lxd#11574]
# Required information

 * Distribution: lxd snap
 * Distribution version: 5.12-c63881f
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.19.0-38-generic
   * LXC version: 5.12
   * LXD version: 5.12
   
# Issue description

When I use LXD feature `lxc config device add/remove` to mount/unmount directory on a virtual machine (not a container), I have noticed that hot-unmount (remove device while the virtual machine is running) is allowed and it causes some unwanted behavior. The message of the device removal command does show it succeeded, but after that, any operations to the hot-unmount directory will cause a hang on the terminal, like `lxc stop` or try to access the hot-unmounted directory in other ways. Furthermore, unmounting while the instance is stopped does not cause this issue. 

# Steps to reproduce

 1. Create a virtual machine, `lxc launch --vm ubuntu: my-vm`
 2. Stop the virtual machine so we can mount `lxc stop my-vm`
 3. Mount a directory to the virtual machine via `lxc config device add my-vm device_1 disk source=<host_diretory> path=<instance_diretory>`, expecting message `Device device_1 added to my-vm`
 4. Start the virtual machine so we can use the mount `lxc start my-vm`
 5. At this moment, the directory is mounted and can be used. If you enter the virtual machine by `lxc exec my-vm bash` and run `findmnt | grep device_1`, you should see the added device
` ├─/native                                     lxd_device_1           virtiofs   rw,relatime` 
 7. Unmount the directory while the virtual machine is running via `lxc config device remove my-vm device_1`, this step succeeded by seeing the message `Device device_1 removed from my-vm`. However, running the command `findmnt | grep device_1` in the virtual machine still shows the device.
 ` ├─/native                                     lxd_device_1           virtiofs   rw,relatime` . It looks like it was not removed correctly. 
 8. Tried to stop the virtual machine by running `lxc stop my-vm`, it will hang.

**Comment by georgeliao** [comment]
Hi @stgraber 
I think QEMU which is the backend of LXD that uses virtiofs and 9p and it supports hot-unplugging. 
About `dmesg`, I did not see anything weird at a glance, and also there is a lot of information, are there any keywords I should focus on?

**Comment by roosterfish** [comment]
I was able to reproduce this.

The reason the VM hangs is due to the fact that LXD stops the corresponding `virtiofsd` process when hot unplugging the directory without removing the device first via `qmp`.

We could achieve hot unplugging, by issuing the following `qmp` command before we close down the virtio process:

* `device_del id=dev-lxd_{device name}-virtio-fs`

Optionally we could also remove the char device afterwards:

* `chardev-remove id=lxd_{device name}`

Inside the VM, this still leaves us the following message when trying to access the mount point:

```bash
root@test:~# cd /mnt
-bash: cd: /mnt: Transport endpoint is not connected
```

But it doesn't leave the VM anymore in a stuck state.

@stgraber @tomponline should we go into this direction, or just disable hot unplugging for VM directories? Hot plugging directories is already disabled for VMs.

**Comment by tomponline** [comment]
Yes lets try and cleanly remove it and the char device.

**Comment by roosterfish** [comment]
@ricab yes if you perform an `umount` the message goes away. But there is more to it, I am linking the thread here for a more in depth look: https://github.com/canonical/lxd/pull/11916#issuecomment-1623386489.

What I didn't already see in the post above is that the `device_del` operation has way more impact than anticipated.
