### ISSUE TITLE
Network zone records disappear after container restart when using OVN

### ISSUE THREAD

**Issue by mandrav** [canonical/lxd#12177]
# Required information

 * Distribution: **Ubuntu**
 * Distribution version: **22.04**
 * The output of "lxc info" or if that fails:
   * Kernel version: **5.15.0-79-generic**
   * LXC version: **5.15**
   * LXD version: **5.15**
   * Storage backend in use: **btrfs**

# Issue description

When using OVN for networking, when a container is restarted its DNS entry in the relevant network zone is gone.

# Steps to reproduce

 1. `lxc launch images:alpine/edge a1` :ok: 
 2. `lxc network list-leases ovn0` (contains entries for `a1`) :ok: 
 3. `dig @127.0.0.1 -p8853 axfr <zone>` (contains entries for `a1`) :ok: 
 4. `lxc restart a1` :ok: 
 5. `lxc network list-leases ovn0` (entries for `a1` are **gone**) :x: 
 6. `dig @127.0.0.1 -p8853 axfr <zone>` (entries for `a1` are **gone**) :x: 

Note that this behavior does not occur when **not** using OVN for networking.

When trying to troubleshoot this, and in hope that this may help someone narrow down the root of the problem, I noticed that the issue occurs **only** when the container contains a config key named `volatile.eth0.last_state.ip_addresses`.

If this key is missing, everything works as expected. This key is only added when using OVN, to the best of my understanding.
Trying to explain this behavior I can only assume that, because this key is present, the container does not ask for a DHCP lease and network zones population relies on network leases. Maybe I 'm wrong but this is what it feels like it's happening.

I hope someone with knowledge of the inner net-workings of LXD can fix this.
Let me know if you need more info.

**Comment by mandrav** [comment]
I forgot to explicitly mention that if you edit the container config, remove the `volatile.eth0.last_state.ip_addresses` config key and restart the container then the network lease is reinstated and its DNS records work again.
During testing, I didn't observe if the IP changed after the edit.

**Comment by tomponline** [comment]
@MusicDin would you be interested in taking a look into this one for me? Thanks

**Comment by MusicDin** [comment]
When the container is restarted LXD checks the container's `LastStateIPs` against the IPs currently present on the LogicalSwitch. Since the LogicalPort associated with this specific container is deleted during the stop operation, the IPs from LastStateIPs are unlikely to match any existing IPs. This is expected behavior.

The problem arises at this point: LXD automatically categorizes any IPs not found in the existing list as static. This incorrect assumption causes dynamic IPs to disapper from the list of network leases, as they are mistakenly treated as static IPs.

Before restart:
```
sudo ovn-nbctl list logical_switch_port lxd-net18-instance-418a52a6-f1f3-4d25-b2a8-1f2e78d7546a-eth0

name                : lxd-net18-instance-418a52a6-f1f3-4d25-b2a8-1f2e78d7546a-eth0
addresses           : ["00:16:3e:74:84:66 dynamic"]
dynamic_addresses   : "00:16:3e:74:84:66 10.130.232.2 fd42:36b4:5848:91b4:216:3eff:fe74:8466"
...
```

After restart:
```
sudo ovn-nbctl list logical_switch_port lxd-net18-instance-418a52a6-f1f3-4d25-b2a8-1f2e78d7546a-eth0 

name                : lxd-net18-instance-418a52a6-f1f3-4d25-b2a8-1f2e78d7546a-eth0
addresses           : ["00:16:3e:74:84:66 10.130.232.2 fd42:36b4:5848:91b4:216:3eff:fe74:8466"]
dynamic_addresses   : []
...
```

While this is not a solution, commenting line https://github.com/canonical/lxd/blob/f0be0b9da62b37400be4b3c81319e8adec071d8e/lxd/network/driver_ovn.go#L3535 demonstrates that this issue does not occur if IPs are not provided when creating new LogicalSwitchPort.

**Comment by tomponline** [comment]
thanks for that chat this morning, as discussed lets get `lxc network list-leases <ovn network>` working for proper statically configured IPs first and that should fix the other issue here.
