### ISSUE TITLE
`loki.api.url` should discard any provided `/loki/api/v1/push`

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12271]
When configuring integration with Loki, one provides LXD with the URL to Loki's API. Since a URL can include the path, a user may do `lxc config set loki.api.url=http://10.76.66.141:3100/loki/api/v1/push`. The problem is that LXD unconditionally appends `/loki/api/v1/push` to the provided URL resulting in bogus HTTP POSTs to `http://10.76.66.141:3100/loki/api/v1/push/loki/api/v1/push`.

The doc on `loki.api.url` is pretty succinct so I think it's a fair mistake for someone to do, at least I think I did when implementing the charm because the Loki integration lib returns `http://${hostname|ip}:3100/loki/api/v1/push` and I feed that directly to LXD. While I could fix the charm, I think the LXD side should be improved. Either by dropping any provided `/loki/api/v1/push` suffix or by rejecting the value as bogus.

**Comment by monstermunchkin** [comment]
I prefer dropping the `/loki/api/v1/push` if provided by the user.

**Comment by tomponline** [comment]
My preference would be to improve the docs and explain that LXD will add the `/loki/api/v1/push` to the URL, otherwise this url setting will be a special case compared to other ones (such as the ones we use for interacting with external auth providers, where we also append certain paths to the end).

Also if we start stripping stuff from the URL that the user provides we don't know if they do infact need that, perhaps to get through a reverse proxy to their loki server.
