### ISSUE TITLE
storage limits not working when first starting lxd service

### ISSUE THREAD

**Issue by swebbyIT** [canonical/lxd#12343]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 lts
 * The output of "lxc info" or if that fails:
   * Kernel version: 
   * LXC version: 
   * LXD version: 5.18
   * Storage backend in use: nvme?

# Issue description

I have various containers with storage limits (example: limits.read= 20MB & limits.write=20MB). When I start the server and then start the lxd service starting all the containers, that limit doesn't work making the container use more resources. If I restart the single container it works.

# Steps to reproduce

 1. start the server with lxd installed
 2. create a container
 3. Set storage limits.read & write
 4. restart the server
 5. after starting the containers enter the container and test the write and read speed with "fio" - limits don't work here
 6. restart the container and repeat the step 5- it works before restart

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by swebbyIT** [comment]
If I can be useful for tests or confirmations on this point, I remain available.

**Comment by monstermunchkin** [comment]
I was able to reproduce this, and can confirm that this is a bug.

**Comment by monstermunchkin** [comment]
This bug was introduced in ba24d18dcba4fca6f55f264ef5d9bf3fafd2e1be.

**Comment by monstermunchkin** [comment]
This is actually also an issue when stopping the container and then starting it again.

The issue is that the `IsRunning` function returns `false` when starting (not restarting) the container. Previously it returned `true`. That causes the `DeviceEventHandler` function to exit before anything is done as that function calls `IsRunning`. And since `DeviceEventHandler` exits early, `deviceAddCgroupRules` is not called, and therefore no cgroup limits are applied.

/cc @tomponline
