### ISSUE TITLE
`5.0/edge` re-enabling `security.devlxd` fails

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12656]
```
# lxc launch ubuntu-daily:22.04 v1 --vm
# sleep 30
# lxc config set v1 security.devlxd false
# sleep 10
# lxc config unset v1 security.devlxd
Error: Failed sending VM sock address to lxd-agent: not authorized
```

Additional information:

```
# snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-ccdba5c  26494  5.0/edge  canonical✓  -
```

Note: this **works** with `latest/edge`.

**Comment by tomponline** [comment]
Thanks, this will likely be fixed by https://github.com/canonical/lxd/pull/12634 once its backported

**Comment by tomponline** [comment]
Should be fixed by [devlxd](https://github.com/canonical/lxd/pull/12674/commits/03ff42d5befae18a07748422a88abf80dc9f5c61)

**Comment by tomponline** [comment]
@simondeziel please can you let me know if fixed in 5.0/edge, thanks.

**Comment by simondeziel** [comment]
@tomponline still not fixed in `5.0/edge`:

```
ubuntu@a2x4:~$ snap list lxd
Name  Version      Rev    Tracking  Publisher   Notes
lxd   git-3afa7f6  26630  5.0/edge  canonical✓  -
ubuntu@a2x4:~$ lxc config set v1 security.devlxd false
ubuntu@a2x4:~$ lxc config unset v1 security.devlxd
Error: Failed sending VM sock address to lxd-agent: not authorized
```

**Comment by MusicDin** [comment]
This is because we are not allowing GET requests within `devlxdAPIGet` if `security.devlxd` is not enabled.

5.0-stable:
https://github.com/canonical/lxd/blob/c5e298c251521213b8f354afbe9e2e058fa15fc7/lxd/devlxd.go#L181-L185

In latest version (main branch) `devlxdAPIGet` has been replaced with `devlxdAPIHandler`.
Within the function we check for the `security.devlxd` only if request method is PATCH, therefore it works.
https://github.com/canonical/lxd/blob/6605050f32f5ccd0c36ab0bb845b79d7b98fd35a/lxd/devlxd.go#L183-L211

@tomponline should I open a PR to disable this check, or are we planning to port the new `devlxdAPIHandler`?

**Comment by tomponline** [comment]
@simondeziel this isn't a regression between 5.0/stable and 5.0/edge is it?

@MusicDin when the new handler logic was landed in main, was there an accompanying API extension that the tests can check for and skip for 5.0 LTS?
