### ISSUE TITLE
`lxc file push --mode` doesn't update the permission of existing target file

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12724]
Steps to reproduce:

```
$ lxc launch ubuntu-daily:22.04 u1
Creating u1
Starting u1
$ lxc exec u1 -- ls -l /etc/hostname
-rw-r--r-- 1 root root 3 Jan 11 18:31 /etc/hostname
$ echo foo | lxc file push --mode 0664 - u1/etc/hostname
$ lxc exec u1 -- ls -l /etc/hostname
-rw-r--r-- 1 root root 4 Jan 11 18:38 /etc/hostname
$ lxc exec u1 -- cat /etc/hostname
foo
```

So the content is updated but the mode isn't change. A workaround is to `lxc file delete u1/etc/hostname` prior to pushing.

Additional information:

```
$ snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-e676fc6  26653  latest/edge  canonical✓  -
```

**Comment by MggMuggins** [comment]
It may be better to describe the issue as "`X-LXD-mode` fails to change mode for existing files", as it's currently [being ignored](https://github.com/canonical/lxd/blob/main/lxd/instance_file.go#L479). Solutions:

1. Always change the mode using `X-LXD-mode` (or not if unset/`-1`), and only send `X-LXD-mode` when `--mode` is passed to the client. This breaks existing behavior as all new pushes will take the umask of the instance's SFTP server instead of the mode of the file on the client. From the API's perspective I think this is the "correct" behavior.
2. Add a header `X-LXD-change-mode` `change` or `retain` (or similar), with default `retain`. I don't love this approach but it allows the client to use the existing behavior.

All of this also applies to `X-LXD-uid` and `X-LXD-gid`. 1 breaks API, 2 is kinda ugly IMO; can I get a second opinion here?

**Comment by masnax** [comment]
@MggMuggins So in your first approach, can you explain how
> This breaks existing behavior as all new pushes will take the umask of the instance's SFTP server instead of the mode of the file on the client.

If `X-LXD-mode >= 0`, then we already try to set the mode of any file that doesn't already exist on the target, so I think those would be unchanged. Pre-existing files are currently ignore the `X-LXD-mode`, so those would be captured by that case. 

The only unexpected behaviour I can see is this:
* `X-LXD-mode` is `>= 0` without the user specifying the `--mode` flag 
* The file already exists, and so the default `X-LXD-mode` is applied to the file on the destination.

But we already do that for any file that does not already exist, so it would just bring all pushes in line.

**Comment by masnax** [comment]
There's also a private [noModeChanges](https://github.com/canonical/lxd/blob/fa78aa80d517892abaf54cd0d01c2f36e6b261c4/lxc/file.go#L644) toggle in the CLI I noticed.

We can expose that as a CLI flag so a user can explicitly avoid LXD auto-setting the file mode without adding a new header.

**Comment by masnax** [comment]
Ah I missed that you wanted to remove setting `X-LXD-mode` to the mode of the file on the client by default. So I guess my question above is actually "why do we need to remove it in that case?"

**Comment by MggMuggins** [comment]
The only reason not to set `X-LXD-mode` on the client by default is so that the mode is not updated when an existing file is overwritten (the current behavior). For clarity's sake, what I'm proposing with option 1 is to remove [this condition check](https://github.com/canonical/lxd/blob/fa78aa80d517892abaf54cd0d01c2f36e6b261c4/lxd/instance_file.go#L479) and update the file's mode/ownership any time that `X-LXD-mode/uid/gid` are passed.

Exposing `noModeChange` seems like a reasonable compromise here if we do want to break the API in this way. I would argue though that since it also impacts file ownership, it should be renamed to `noPermChange` or similar.

Thanks for taking a look at this; let me know what you think.

**Comment by masnax** [comment]
I see, so basically our choices are:

1. By default always set the file mode to the mode from the client, regardless of if the file exists at the destination. This breaks the existing API as currently the destination mode is always preserved.

2. By default never set the file mode to the mode from the client unless `--mode` is specified. This breaks the existing API as currently any file that does not already exist at the destination will be set to the mode of the file on the client.

3. Add a new request header, or modify the existing headers to inform the target server whether the mode was determined by the user with `--mode` or by LXD. Then if the file does exist at the destination, only set the mode if it was user-specified.

And whichever we choose would have to apply to all of `X-LXD-mode`, `X-LXD-uid` and `X-LXD-gid`. So it's all permissions, not just mode.

I think I agree with you that option 2 seems the most "correct". The mode itself is less of a concern to me here than the wonkiness of uids/gids from the source automatically appearing on the destination. The code is also quite old so I'm not sure what the reason was to do it this way to begin with. I'll leave it to @tomponline to make the final call though.

If we do decide to go with option 3, we might be able to just re-use the `X-LXD-{uid,gid,mode}` headers and just modify them to include `{true,false},0777` which is then parsed by the other side, rather than introducing 3 whole new headers. The `ParseLXDFileHeaders` function would probably have to be updated to return a struct instead if we go with option 3 because otherwise it would be returning 7 values which is just an eyesore.

**Comment by tomponline** [comment]
Lets go with an API extension and a modification to each of the headers to append an indicator if the option was explicitly specified by the user.

We need to make sure newer clients work against older servers and vice versa.

**Comment by ru-fu** [comment]
@MggMuggins I'm trying to update the docs for this, but I have a hard time understanding the change.
Is it only for the API and not for the CLI command?

If I try the original reproducer steps, the permissions aren't updated, so I get exactly what is in the example.
This is running on lxd (edge) git-568750c.

**Comment by tomponline** [comment]
> If I try the original reproducer steps, the permissions aren't updated, so I get exactly what is in the example.
> This is running on lxd (edge) git-568750c.

thats concerning @MggMuggins

**Comment by MggMuggins** [comment]
Confirmed that the original reproducer does not set the permissions correctly.
