### ISSUE TITLE
API: Stop embedding post & put structs in info structs to avoid inappropriate fields being present

### ISSUE THREAD

**Issue by samuelallan72** [canonical/lxd#12993]
https://documentation.ubuntu.com/lxd/en/latest/api/#/instances/instance_get shows that `restore` is supposed to be a field in the instance metadata response, however this is not the case.  It appears that the `restore` field should only be used for PUT requests for an instance.

I guess the reason this is because Instance embeds InstancePut.

**Comment by tomponline** [comment]
Yes this is likely due to the use of struct embedding in the in the `Instance` type:

https://github.com/canonical/lxd/blob/main/shared/api/instance.go#L204

Because the docs are generated from the types themselves im not sure if we can specify to exclude certain fields.

@ru-fu do you know if swagger metadata can be instructed to exclude certain fields from the docs?

I don't think we can remove/change the `InstancePut` being embedded in the `Instance` type as this would potentially cause an API break for people using the Go client SDK definitions in their Go programs.

**Comment by tomponline** [comment]
Yes potentially because when interaction (accessing or instantiating) an `Instance` one may directly refer to the embedded `InstancePut` struct.

Also I would want us to fix the overall *theme* here (embedding post and put structs into the info struct) so that its consistent for all entity types, rather than just fixing the particular Instance type.

This is because we may have similar situations occur in the future where a field is added to a post or put struct that subsequently inadvertently affects the resulting info struct with a field that isn't relevant.

So this would be a review and potential change for all LXD API info types.
