### ISSUE TITLE
Networks of type physical managed do not expose state

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#13553]
# Required information

 * Distribution: snap
 * Distribution version: 5.21

# Issue description

The `GET 1.0/networks/:name/state` endpoint returns 404 if the network is a managed physical network.

# Steps to reproduce

 1. Create a physical managed network `lxc network create foo --type physical parent=wlp0s20f3`
 2. Fetch the network state `lxc network info foo`
 3. `Error: Network interface "foo" not found` is returned because  `GET 1.0/networks/foo/state` returns 404. I would expect it to return something.

**Comment by tomponline** [comment]
Whilst I agree this is a bug, I am not entirely sure what we should return here for this endpoint.

The problem is that for `physical` networks, the parent interface can disappear from the host if used by an `physical` NIC, and so most of the info will not be retrievable, or worse only retrievable when the instance isn't running (and the parent interface has been released back to the host).

But when the physical parent is being used as an OVN uplink it might be quite useful to see the counters of data flowing through it.

@edlerd would it be acceptable to sometimes return 404 on this endpoint if the parent interface is missing, either because its not been configured on the host or if its passed into a running instance?
