### ISSUE TITLE
`lxc launch` and `lxc init` shell completions improvements

### ISSUE THREAD

**Issue by kadinsayani** [canonical/lxd#14209]
`lxc launch [TAB]` should show `images:` remote, and complete possible images
`lxc init [TAB]` should show `images:` remote, and complete possible images

**Comment by kadinsayani** [comment]
@simondeziel @tomponline, thought on this? Initially, we decided to exclude simplestreams remotes like `images` and `ubuntu`, but I’ve tested them locally and found that fetching images from these remotes doesn’t cause significant latency. I’m open to any feedback or suggestions you may have.

**Comment by MusicDin** [comment]
Not sure how this would impact LXD remotes, but for simplestream remotes I think we cache the streams and products (images) for 1 hour.

**Comment by simondeziel** [comment]
Completing with the name of the remotes should essentially be free in terms of latency as the data is all local. Good idea IMHO.

For the specific images, isn't `lxc launch $remote:<tab>` all happening client side? If so, how is caching working?

**Comment by MusicDin** [comment]
> For the specific images, isn't lxc launch $remote:<tab> all happening client side? If so, how is caching working?

It has to fetch the [products](https://images.lxd.canonical.com/streams/v1/images.json) from the remote, which is just a json file. Then it caches the file to avoid re-fetching it every time images are listed (searched for). Therefore, the *impact* should be just on *first `[TAB]`* if the file is not already cached (or if the cache expired). Later auto-completions should be near instantaneous. 

IMO this would be a really great addition, since I find myself many times in the situations where I forget the exact image alias and need to check them first :)

**Comment by simondeziel** [comment]
Thanks @MusicDin, I indeed see great usability improvement if what you describe works to leverage the locally cached files. Thank you both.

**Comment by kadinsayani** [comment]
Thanks for clarifying the caching @MusicDin, and thanks for the input @simondeziel. I've put up a PR with the change. It's a very small change for a great usability improvement :).

**Comment by kadinsayani** [comment]
There is slight observable latency with my proposed change, even though there's only one API request happening with the first [TAB]. This is likely due to iterating over the full map of remotes for each completion. Go map lookups are already pretty efficient so I don't think there is much we can do in terms of optimization. We could consider storing a tree structure for image remotes and implement a better search, but I think it would be overkill for this improvement 😅.

**Comment by MusicDin** [comment]
Can you point me where image alias are extracted for auto completion?

**Comment by kadinsayani** [comment]
> Can you point me to where image alias are extracted for auto completion?

https://github.com/kadinsayani/lxd/blob/1bf2447c5f82e0f38bbe7d13ad2834e919310a0e/lxc/completion.go#L1099-L1100

We're just iterating over the already populated `config.Remotes`.

**Comment by MusicDin** [comment]
Is this feature to auto-complete remotes or also the images?
For example if I run `lxc launch images:kali[TAB]` will it recommend `/cloud`?

The `config.Remotes` contains locally configured and static remotes. This list contains for example `ubuntu:`, `images:`, etc. but to fetch the image aliases you need to retrieve the actual metadata of images (products) from the given/selected remote. But since you said that there is slight delay, maybe I've just misunderstood something?

**Comment by kadinsayani** [comment]
Sorry, should have included this as well: https://github.com/kadinsayani/lxd/blob/1bf2447c5f82e0f38bbe7d13ad2834e919310a0e/lxc/completion.go#L176.

**Comment by kadinsayani** [comment]
This is likely the source of the delay: https://github.com/kadinsayani/lxd/blob/1bf2447c5f82e0f38bbe7d13ad2834e919310a0e/lxc/completion.go#L191-L192

**Comment by MusicDin** [comment]
> Sorry, I should have included `cmpImages()` as well: https://github.com/kadinsayani/lxd/blob/1bf2447c5f82e0f38bbe7d13ad2834e919310a0e/lxc/completion.go#L176.

Thanks, I was looking for that :)
