### ISSUE TITLE
Unable to perform manual fsck on LXD Managed Volumes (LVM + ext4)

### ISSUE THREAD

**Issue by declay** [canonical/lxd#14475]
lxd     6.1-78a3d8f  30130  6.1/stable     canonical

I have tried many things and am totally unable to do an fsck on an LXD managed storage volume.
I consider this an operational deficiency since this is a critical thing to perform.

Situation:

* LVM Thin Storage volumes managed by LXD and mounted as a filesystem into the container
* Device under /dev/ shows up when containers are running that reference the storage volume
* When I stop the container the device (/dev/vgx for example) disappears
*  Therefore I have to VG/LV reference to perform and fsck on the LV (with the ext4 filesystem)

I have tried:
* vgchange -ay vgx, but this does not produce the /dev/ entry I need for reference
* Also, lvchange -ay vgx/lv ... (not found)
* vgscan --mknodes (no success)

Question:

* Is there a way for me to do a manual fsck on a suspect LV w/ ext4 on a storage volume managed by LXD?  This is something critical for me to be able to perform in the case of filesystem issues.

Thx!

**Comment by tomponline** [comment]
We have an item on this cycle's roadmap to add support for passing an instance's root volume to another instance for recovery purposes such as this.

However if you need to activate a volume on the host in order to perform manual recovery in the short term, then you should be able to do this by doing what LXD itself does when activating the volume on the host.

https://github.com/canonical/lxd/blob/50dd9149f777206208ce8e165083e25867b41cc3/lxd/storage/drivers/driver_lvm_utils.go#L778

```
lvchange --activate y --ignoreactivationskip vgx/lv...
```
