### ISSUE TITLE
Feature releases inconsistency

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd#14634]
Hey,

With the 5.x releases and prior to that we had a feature release roughly every month. This is also advertised on this repository (https://github.com/canonical/lxd and https://github.com/canonical/lxd/security)  plus  [ubuntu.com](https://documentation.ubuntu.com/lxd/en/latest/support/)

We only had 3 releases this year. March 14 for 5.21, July 8th 6.1 and 6.2 on November 28th

These were also very very big releases instead of the smaller releases we had last year, especially 6.2.

Previously I would get bugfixes within a few weeks and now they took almost 6 months to arrive. I even resorted to running latest/candidate on some LXD hosts to get these fixes quicker.

I'm just curious why this changed :)

**Comment by mionaalex** [comment]
Hi @vosdev

This was not an intentional change. In addition to the three releases you mentioned, we also did 5 feature/bug-fix releases for LXD 5.0 and 4.0, with one more coming soon, plus the MicroCloud LTS release. This takes quite a lot of time and effort, which coupled with several large initiatives we're working on meant we had to push some of the feature releases. Going forward, we are aiming for something in between, not aiming for as frequent as monthly releases, but also not waiting too long and making the releases too big. We'll update the documentation to reflect that.
