### ISSUE TITLE
Ability to run lxd recover as noninteractive

### ISSUE THREAD

**Issue by kautMaks** [canonical/lxd#9153]
Could you make ability to run `lxd recover` as noninteractive.
It needs to run `lxd recover` in bash scripts.

I think would be great something like this:
`lxd recover ctname --backend=dir --source=/var/lib/lxd/storage-pools/default`

`ctname` may be optional, if empty - try to recover all finded ct's

**Comment by oddomatik** [comment]
We have a use-case I believe applicable for exposing "lxd recover" as an API endpoint or accepting input flags.

If a host loses an OS drive (common at our scale), we run ansible playbooks against a freshly imaged machine that detects the scenario and imports the zpool. I'd like to automate the remainder of the process so that we can issue an API command to automatically run the `lxd recover` from an ansible playbook. The input parameters for the recovery process are the same every time, as the zfs pools and storage pools are all deployed the same.

Example... the json will never deviate from this in our recovery process:

`{ "pools": [ { "config": { "source": "<name>", "zfs.pool_name": "<name>" }, "description": "", "name": "<name>", "driver": "zfs" } ] } `

If you have a better suggestion for recovering pools in an automated fashion, or if you can provide pointers for hitting the /internal API as a workaround/temporary alternative, I'm open to it!

**Comment by stgraber** [comment]
You can hit the `/internal/recover` API for this if you really need to, but it's an internal API so subject to change.
We're not likely to be adding this kind of feature to the stable user facing API any time soon though.
